### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [google/sa360-webquery-bigquery#12]
Hello,

I'm an independent security researcher performing security research under the [GitHub Security Lab Bug Bounty Program](https://securitylab.github.com/). I believe I may have found a security vulnerability in this project.

Please open a security advisory against this repository so we can privately discuss the details. This advisory can be opened by a user with admin permissions on this repository.

https://github.com/google/sa360-webquery-bigquery/security/advisories

**Comment by anantdamle** [comment]
Hi @JLLeitschuh you can submit your bug/vulnerability report at [g.co/vulnz](https://g.co/vulnz)

**Comment by JLLeitschuh** [comment]
I have, last Thursday. See: https://issuetracker.google.com/issues/178709136
