### ISSUE TITLE
Insecure Permissions for /datastore/StoredCredential File

### ISSUE THREAD

**Issue by KatTraxler** [google/sa360-webquery-bigquery#14]
The sa360-webquery-biggquery Java program requests authorization from the end user and caches their OAuth2 Access Token and Refresh Token in the StoredCredential File.  
Permissions for this file are: _-rw-r--r-- (744)_ 
This set of file permissions allows the Owner of the file to read and write.  Additionally it allows any other user on the system to read the file.

A file on a local system which stores credentials (even short-term credentials), is a target for malware on the local system.  Access should be restricted to only those users and groups requiring access.  Malware known as '[TeamTNT](https://www.securitymagazine.com/articles/94520-new-teamtnt-malware-targeting-kubernetes)' is known to target endpoints for locally cached credentials for cloud infrastructure.

Due to the sensitive nature of the StoredCredentials File, the file permissions should be changed to: -rw-------.  This would restrict Read and Write operations to the Owner of the File.
Permissions for the 'StoredCredentials' File should match those of the ~/.config/gcloud/access_tokens.db file.
The access_tokens.db file holds the cached access tokens and refresh tokens utilized by gcloud.  The file permission for the access_tokens.db sqlite file is: _-rw-------_ 

XOXO, 
_kat

**Comment by anantdamle** [comment]
Thanks for the issue.
@KatTraxler If you have time, can you please send a PR.

**Comment by KatTraxler** [comment]
I did my best.
PS: I'm not a Java Dev

**Comment by JLLeitschuh** [comment]
The vulnerability has been disclosed here:
https://github.com/JLLeitschuh/security-research/security/advisories/GHSA-7fjx-657r-9r5h

I've moved forward with requesting a CVE number via the MITRE appeals process as Google has been unresponsive as a CNA after multiple requests for CVE numbers for these vulnerabilities.
